### ISSUE TITLE
Gifler not found error 

### ISSUE THREAD

**Issue by kambojakhil1991** [googlecreativelab/teachable-machine#11]
I am trying to build this project
getting error Cannot find module gifler  from .....\src\ouputs
Please help in this

**Comment by HalfdanJ** [comment]
Just to verify, did you run `yarn` or `npm install` successfully? And did it create a folder called `gifler` inside `node_modules`?

**Comment by kambojakhil1991** [comment]
I ran yarn build  and it did not create module
gifler inside node-modules
please suggest solution as i m building it on windows

Thanks for you help
Akhil Kamboj

**Comment by kambojakhil1991** [comment]
Hi

Getting error couldnt find binary git
when ran yarn command

please help


regards
Akhil Kamboj

**Comment by HalfdanJ** [comment]
Ahh so that is because we reference the git version of gifler directly (https://github.com/googlecreativelab/teachable-machine/blob/master/package.json#L46), and you need git installed for that to work. So make sure that you have git installed.

**Comment by kambojakhil1991** [comment]
Hi

Thanks for your help
I resolved it and used command yarn add gifler

and it was built successfully


Regards
Akhil Kamboj

**Comment by HalfdanJ** [comment]
Great

**Comment by kambojakhil1991** [comment]
Hi

Now in my local server when i am launching
camera is not getting on
Any help on this

Regards
Akhil Kamboj

**Comment by HalfdanJ** [comment]
I've experienced that I had to type in localhost instead of the ip address that by default opens up for webcam to work. Try that
