### ISSUE TITLE
I have been trying to use node net package in your output GIFOuput.js .It gives error net.connect is not found

### ISSUE THREAD

**Issue by kambojakhil1991** [googlecreativelab/teachable-machine#13]

**Comment by kambojakhil1991** [comment]
If I use different js file having code to use net then it works but how to make it work in your GIFOutput .js 
Please help

**Comment by kambojakhil1991** [comment]
Please assist if  anybody can tell why I am not able to connect to net package it gives error net.connect is not a method. I am using this in your output file GIFOutput .This is not a issue but if you can help me in this

**Comment by HalfdanJ** [comment]
Am I understanding it correctly that you are trying to use the [net](https://nodejs.org/api/net.html) package inside the gifoutput module?

If thats the case, that wont work since the code is running in the browser, not in nodejs.

**Comment by kambojakhil1991** [comment]
Thanks a lot

Regards
Akhil Kamboj
