### ISSUE TITLE
How can i make the gif images localization?

### ISSUE THREAD

**Issue by ChunyeLi** [googlecreativelab/teachable-machine#15]
I want to use the local images in my computer as the output rather than the url link and i have already modified the url path which exits in the GIFOutput.js to the local images path ,but i still cannot see anything from the output. How can i do?

**Comment by HalfdanJ** [comment]
You would have to serve the files locally in some way that the browser can access them. What type of url path are you using now?

**Comment by ChunyeLi** [comment]
I have replaced the following
"this.defaultGifs.push({
			still: 'https://media1.giphy.com/media/vFKqnCdLPNOKc/giphy-downsized_s.gif',
			gif: 'https://media1.giphy.com/media/vFKqnCdLPNOKc/200w.gif'
		});
        this.defaultGifs.push({
			still: 'https://media1.giphy.com/media/vFKqnCdLPNOKc/giphy-downsized_s.gif',
			gif: 'https://media1.giphy.com/media/vFKqnCdLPNOKc/200w.gif'
		});
	
		this.defaultGifs.push({
			still: 'https://media0.giphy.com/media/I3BLTIP5Gv6h2/giphy-downsized_s.gif',
			gif: 'https://media0.giphy.com/media/I3BLTIP5Gv6h2/200w.gif'
		});"
with the following
"this.defaultGifs.push({
			still: 'file://Users/C316/Desktop/lichunye/teachable-machine-mastert/src/outputs/dog.gif ',
			gif: 'file://Users/C316/Desktop/lichunye/teachable-machine-mastert/src/outputs/dog.gif '
		});

		this.defaultGifs.push({
			still: 'file://Users/C316/Desktop/lichunye/teachable-machine-mastert/src/outputs/cat.gif ',
			gif: 'file://Users/C316/Desktop/lichunye/teachable-machine-mastert/src/outputs/cat.gif  '
		});

		this.defaultGifs.push({
			still: 'file://Users/C316/Desktop/lichunye/teachable-machine-mastert/src/outputs/rabbit.gif',
			gif: 'file://Users/C316/Desktop/lichunye/teachable-machine-mastert/src/outputs/rabbit.gif'
		});"

How should i modified the url  path ?
Among the files and url paths which one should be modified?
thanks~

**Comment by ChunyeLi** [comment]
I have replaced the following

         this.defaultGifs.push({
                still: 'https://media1.giphy.com/media/vFKqnCdLPNOKc/giphy-downsized_s.gif',
                gif: 'https://media1.giphy.com/media/vFKqnCdLPNOKc/200w.gif'
         });

         this.defaultGifs.push({
                still: 'https://media1.giphy.com/media/vFKqnCdLPNOKc/giphy-downsized_s.gif',
                gif: 'https://media1.giphy.com/media/vFKqnCdLPNOKc/200w.gif'
        });

	this.defaultGifs.push({
		still: 'https://media0.giphy.com/media/I3BLTIP5Gv6h2/giphy-downsized_s.gif',
		gif: 'https://media0.giphy.com/media/I3BLTIP5Gv6h2/200w.gif'
	});

with the following

        this.defaultGifs.push({
              still: 'file://Users/C316/Desktop/lichunye/teachable-machine-mastert/src/outputs/dog.gif ',
              gif: 'file://Users/C316/Desktop/lichunye/teachable-machine-mastert/src/outputs/dog.gif '
        });

	this.defaultGifs.push({
		still: 'file://Users/C316/Desktop/lichunye/teachable-machine-mastert/src/outputs/cat.gif ',
		gif: 'file://Users/C316/Desktop/lichunye/teachable-machine-mastert/src/outputs/cat.gif  '
	});

	this.defaultGifs.push({
		still: 'file://Users/C316/Desktop/lichunye/teachable-machine-mastert/src/outputs/rabbit.gif',
		gif: 'file://Users/C316/Desktop/lichunye/teachable-machine-mastert/src/outputs/rabbit.gif'
	});

How should i modified the url path ?
Among the files and url paths which one should be modified?
thanks~

**Comment by HalfdanJ** [comment]
I dont think chrome will allow that you try and load files from a `file://` path. You will have to instead move the files so they are hosted by the local webserver. You can put them in the `assets` folder, that way they will be hosted like all the other assets of the project.

**Comment by HalfdanJ** [comment]
Closing this issue now, but feel free to continue commenting
