### ISSUE TITLE
win10 - not working with latest chrome, online or offline . .

### ISSUE THREAD

**Issue by kekGH** [googlecreativelab/teachable-machine#16]
Works online with firefox . . .

**Comment by HalfdanJ** [comment]
We are not able to reproduce this issue. Can you be more specific what you meant that doesn't work? 

Also, teachable machine needs to download the squeezenet model from the internet, so unless its cached in your browsers, it wont work offline.

**Comment by kekGH** [comment]
On the main page,
https://teachablemachine.withgoogle.com/ , opened w/chrome, before clicking
'Let's Go' or 'skip the tutorial',
there is already a console message;

'Uncaught DOMException: Failed to read the 'localStorage' property
cast_sender.js:69
from 'Window': Access is denied for this document.'

After clicking 'skip the tutorial', popup (1) shows '
https://teachablemachine.withgoogle.com wants to Use your camera' (clicked
Allow).

=> new popup (2) 'To teach your machine, you need to click up here to turn
on your camera and then refresh the page.'
=> back on On the main page and the only difference after refresh and click
of 'skip the tutorial', there is no popup (1),
but popup(2) and the same console message (Uncaught DOMException: . . .).

With firefox, On the main page, https://teachablemachine.withgoogle.com/ ,
there are console messages;
- unreachable code after return statement [Learn More] bundle.js:5098:4
- unreachable code after return statement [Learn More] js:64:1196
but I can teach the machine just fine . .

I tried to compile standalone version with yarn, but got some errors;
unreachable code after return statement [Learn More]
bluebird.js:5096
Loading failed for the <script> with source “
https://www.googletagmanager.com/gtag/js?id=UA-107306747-1”.
127.0.0.1:3000:312
Error: manifest.json not found at
https://storage.googleapis.com/learnjs-data/checkpoint_zoo/squeezenet1_1/.
[object ProgressEvent]

__

**Comment by ChunyeLi** [comment]
Hello~can you make it work with chrome, offline?

**Comment by kekGH** [comment]
Finally, after re-installing chrome online and offline work fine.
thx

**Comment by kekGH** [comment]
Problem solved!
