### ISSUE TITLE
How can I add one or more new classes to train?

### ISSUE THREAD

**Issue by WeiZhiHuang** [googlecreativelab/teachable-machine#17]
It's only 3 classes in the origin, then I want to train more classes.
Is it possible?
I found the green, purple, orange, and red in the code, but the red one wasn't used, maybe we can use it?
But I'm poor in it, so I don't know how to modify this project to train more.
May anyone help me with this?
thx.

**Comment by HalfdanJ** [comment]
We are working on an example that shows how to do it.

**Comment by WeiZhiHuang** [comment]
Okay, thanks for your reply.
