### ISSUE TITLE
Error running yarn run watch

### ISSUE THREAD

**Issue by gotnull** [googlecreativelab/teachable-machine#2]
<img width="1164" alt="screen shot 2017-10-04 at 3 36 24 pm" src="https://user-images.githubusercontent.com/578908/31160125-d5fa9084-a919-11e7-9ba0-a77f3b0b958c.png">

**Comment by ashu17706** [comment]
@gotnull How did you fixed this error ? I am also getting the same error.

**Comment by gotnull** [comment]
@ashu17706 Run `yarn build` first!

**Comment by ashu17706** [comment]
@gotnull Yes. Thanks man :)

**Comment by HalfdanJ** [comment]
Thanks @gotnull  for pointing that out, I've updated the readme to reflect that.
