### ISSUE TITLE
Any idea how to add serialport to this project?

### ISSUE THREAD

**Issue by mohsenpashna** [googlecreativelab/teachable-machine#20]
Hi,
I am not quite familiar with JavaScript, but I and Damon [one of my friends] thought it would be even more amazing if we can add serial port to the output of the system so that we can send some characters to the Arduino.

I tried something on npm, but constantly get an error to import serialport to the output class. 

Any idea or thought?

Thanks
Mohsen

**Comment by HalfdanJ** [comment]
You can use a library like this: https://github.com/webusb/arduino it connects to the Arduino over WebUSB, I've successfully also been doing something similar with this codebase.
