### ISSUE TITLE
How to open other files in output inplace of gif images.?

### ISSUE THREAD

**Issue by vvkiiit** [googlecreativelab/teachable-machine#21]
In output it's displaying gif images, I want to open any document files in place of gif image how to modify the code.

**Comment by HalfdanJ** [comment]
The current gif output is really made for the giphy api, but you could make you own output like these: https://github.com/googlecreativelab/teachable-machine/tree/master/src/outputs 

Alternatively you can build something from the boilerplate code: https://github.com/googlecreativelab/teachable-machine-boilerplate
