### ISSUE TITLE
Any instrucctions to run with PM2 or similar?

### ISSUE THREAD

**Issue by luiscosio** [googlecreativelab/teachable-machine#4]
First of all, kudos on this amazing machine learning example.

We are working on localizing it for LATAM, it's an invaluable resource that we want to use it to show what machine learning is capable of doing.

Since we are expecting some traffic, budo doesn't seem like the right choice, so we are trying to serve it using PM2, with no success.

Do you have any suggestions/alternatives?

**Comment by HalfdanJ** [comment]
Thanks!

The project is made for hosting on AppEngine. You can create a project there, and deploy to it using the `gcloud app deploy` command line tools for Google Cloud.

**Comment by luiscosio** [comment]
Easy peasy, runs like a charm! 

https://teachable-machine.appspot.com/

We've just finished translating the wizard and most of the UI, just missing a couple of texts and the custom domain and we are good to go, thank you so much!

**Comment by rojeh1995** [comment]
perfect!
