### ISSUE TITLE
issue with yarn 

### ISSUE THREAD

**Issue by Yang-YiFan** [googlecreativelab/teachable-machine#5]
I typed `yarn` in terminal. but this error popes out.
`ERROR: There are no scenarios; must have at least one.`
Do I have to install some other thins?
PS: I run the code on my Ubuntu 16.04 system locally.
Thanks:-)

**Comment by HalfdanJ** [comment]
It looks like that error comes from using a wrong version of yarn: https://github.com/yarnpkg/yarn/issues/2821
