### ISSUE TITLE
Clicking causes section to restart at "Ok, you should now see the green bar" stage in the tutorial

### ISSUE THREAD

**Issue by arkadyark** [googlecreativelab/teachable-machine#9]
Steps to reproduce:

1. Complete tutorial up to the step at which the instructor says "Ok, you should now see the green bar (...)"
2. Click anywhere on the screen as that (long) step is being played

At this point, the stage restarts. This is particularly annoying in this longer stage where one may become impatient and begin clicking around.

**Comment by HalfdanJ** [comment]
Thanks
